<?php
/**
 * Client automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace SdkFabric\Discord;

use GuzzleHttp\Exception\BadResponseException;
use Sdkgen\Client\ClientAbstract;
use Sdkgen\Client\Credentials;
use Sdkgen\Client\Exception\ClientException;
use Sdkgen\Client\Exception\UnknownStatusCodeException;

class Client extends ClientAbstract
{
    public function channel(): ChannelTag
    {
        return new ChannelTag(
            $this->httpClient,
            $this->parser
        );
    }



    public static function build(string $clientId, string $clientSecret, ?TokenStoreInterface $tokenStore = null, ?array $scopes = null): self
    {
        return new self('https://discord.com/api/v10', new Credentials\OAuth2($clientId, $clientSecret, 'https://discord.com/api/oauth2/token', 'https://discord.com/oauth2/authorize', $tokenStore, $scopes));
    }
}
