<?php
/**
 * MessageAllowedMentions automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace SdkFabric\Discord;

use PSX\Schema\Attribute\Description;
use PSX\Schema\Attribute\Key;

#[Description('')]
class MessageAllowedMentions implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    /**
     * @var array<string>|null
     */
    #[Description('An array of allowed mention types to parse from the content')]
    protected ?array $parse = null;
    /**
     * @var array<string>|null
     */
    #[Description('Array of role_ids to mention (Max size of 100)')]
    protected ?array $roles = null;
    /**
     * @var array<string>|null
     */
    #[Description('Array of user_ids to mention (Max size of 100)')]
    protected ?array $users = null;
    #[Key('replied_user')]
    #[Description('For replies, whether to mention the author of the message being replied to (default false)')]
    protected ?bool $repliedUser = null;
    /**
     * @param array<string>|null $parse
     */
    public function setParse(?array $parse): void
    {
        $this->parse = $parse;
    }
    /**
     * @return array<string>|null
     */
    public function getParse(): ?array
    {
        return $this->parse;
    }
    /**
     * @param array<string>|null $roles
     */
    public function setRoles(?array $roles): void
    {
        $this->roles = $roles;
    }
    /**
     * @return array<string>|null
     */
    public function getRoles(): ?array
    {
        return $this->roles;
    }
    /**
     * @param array<string>|null $users
     */
    public function setUsers(?array $users): void
    {
        $this->users = $users;
    }
    /**
     * @return array<string>|null
     */
    public function getUsers(): ?array
    {
        return $this->users;
    }
    public function setRepliedUser(?bool $repliedUser): void
    {
        $this->repliedUser = $repliedUser;
    }
    public function getRepliedUser(): ?bool
    {
        return $this->repliedUser;
    }
    public function toRecord(): \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = new \PSX\Record\Record();
        $record->put('parse', $this->parse);
        $record->put('roles', $this->roles);
        $record->put('users', $this->users);
        $record->put('replied_user', $this->repliedUser);
        return $record;
    }
    public function jsonSerialize(): object
    {
        return (object) $this->toRecord()->getAll();
    }
}
